### ISSUE TITLE
Use :first-child

### ISSUE THREAD

**Issue by LukyVj** [LukyVj/family.scss#10]
Use `:first-child` instead of `:nth-child(1)`
`:first-child` == IE7/8 
`:nth-child` == IE9

https://developer.mozilla.org/fr/docs/Web/CSS/:nth-child
https://developer.mozilla.org/fr/docs/Web/CSS/:first-child

**Comment by LukyVj** [comment]
This `:first-child` change will occur on a next release of a better **Family.scss**.

There is actually no mixins that uses `:nth-child(1)` directly.
To make it happen, I'll use a Sass **if/else** statement.

Introducing this change right now may seems weird, since I just released the library.

**Comment by LukyVj** [comment]
fixed in 003472a51b7db3e25068c00c63121e78cca96bf2

**Comment by qikkeronline** [comment]
@LukyVj just a heads-up; I can't seem to find this fix in the latest build (or I am missing it somehow 👍 )

**Comment by LukyVj** [comment]
Hey, thanks for the heads up! You're right, I added it in the sass file from the components folder, but I forgot to update the source file. 

You can find it here https://github.com/LukyVj/family.scss/blob/master/source/stylesheets/vendors/_family.scss

Updating it now!

**Comment by LukyVj** [comment]
Here you go https://github.com/LukyVj/family.scss/blob/master/source/src/family.scss#L5-L16

**Comment by qikkeronline** [comment]
Awesome, thanks so much!
