### ISSUE TITLE
middle() not re-drawing on adding/removing children

### ISSUE THREAD

**Issue by tornography** [LukyVj/family.scss#11]
When adding or removing children, element 6 stays the marked one.

**Comment by LukyVj** [comment]
Yes, this is normal.

Let's see the example : 

![](http://puu.sh/p29IO/7f39b7d54d.png) 

Here, you have 11 element, it's an odd number, so on both sides of the selected element, you'll find the same amount of children ( 5 on both sides ). 
So the **N°6** is the middle item. 

Now, what happen if I change the number of items to 17 : 

![](http://puu.sh/p29Op/afe0fe97e9.png)

Answer : Nothing, until I change the value of `middle(n)`. I now have 17 items, so I'll write `middle(17)`, and the result : 

![](http://puu.sh/p29RL/7f2a48f475.png)

**Comment by tornography** [comment]
Oh. My bad. You're right.

**Comment by LukyVj** [comment]
No problem :) 
I admit the docs can lack of expainations, I'll improve that!

**Comment by Haroenv** [comment]
You could change the number in `middle` on adding/removing a child to make it more clear.
