### ISSUE TITLE
Could this be added to NPM

### ISSUE THREAD

**Issue by jonathan-fielding** [LukyVj/family.scss#12]
Hello, 

May I ask this is added to NPM please, this would allow those of us who use it for all package management to use it easily

Thanks

Jonathan

**Comment by benjamincharity** [comment]
I would second this. Also adding Bower since many client side projects haven't made the switch to NPM over Bower.

**Comment by LukyVj** [comment]
Hey guys, I'll take care of this on the following days. 
Thanks for your support!

**Comment by Haroenv** [comment]
I'm wondering how you'd use `scss` from `npm`. Would that be installing it and getting the file out of `node_modules` or do you use some tool?

**Comment by benjamincharity** [comment]
@Haroenv I haven't yet made the switch, but from what I've read it would require something like webpack/gulp/grunt to wire up resources from the `node_modules` folder. (I've seen many tutorials on how to do so when dealing with Bootstrap files)

**Comment by michael-jahn-dev** [comment]
@Haroenv for Compass just use `add_import_path` in your `config.rb` to point to the package or via Grunt for example with `grunt-sass` package you can add the option `includePaths` which also points to the package located under `node_modules`. Then you just `@import` the `family.scss`. 
This also works for bower obviously.

**Comment by jonathan-fielding** [comment]
node-sass and has include paths which allows you to include npm modules very easily, as gulp-sass wraps this it also supports it

**Comment by LukyVj** [comment]
Hey guys, 

Here you go! https://www.npmjs.com/package/family.scss

**Comment by LukyVj** [comment]
Also you should now be able to `bower install family.scss` :)
