### ISSUE TITLE
What is the current browser support for these mixins?

### ISSUE THREAD

**Issue by benjamincharity** [LukyVj/family.scss#14]
Hate dealing with crazy nth cases so this looks like a great utility.. wondering if anyone has tested the browser coverage on this?

**Comment by vank0** [comment]
They work on all modern browsers all the way down to IE9 :)

**Comment by Haroenv** [comment]
According to [doiuse](http://www.doiuse.com/?url=&browsers=&css=*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20first%283%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-child%28-n%20%2B%203%29%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20last%283%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-last-child%28-n%20%2B%203%29%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20after-first%285%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-child%28n%2B6%29%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20from-end%283%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-last-child%283%29%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20between%283%2C%206%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-child%28n%2B3%29%3Anth-child%28-n%2B6%29%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20pair-between%283%2C%2012%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-child%28even%29%3Anth-child%28n%20%2B%203%29%3Anth-child%28-n%20%2B%2012%29%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20impair-between%283%2C%2013%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-child%28odd%29%3Anth-child%28n%20%2B%203%29%3Anth-child%28-n%20%2B%2013%29%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20all-but%283%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anot%28%3Anth-child%283%29%29%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20each%283%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-child%283n%29%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20every%283%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-child%283n%29%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20from-first-last%282%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-child%282%29%2C%20ul%20li%3Anth-last-child%282%29%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20middle%2811%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-child%286%29%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20all-but-first-last%282%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-child%28n%2B2%29%3Anth-last-child%28n%2B2%29%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20first-of%2810%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-last-child%2810%29%3Afirst-child%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20last-of%2810%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-of-type%2810%29%3Anth-last-of-type%281%29%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20pair%28%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-child%28even%29%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20even%28%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-child%28even%29%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20impair%28%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-child%28odd%29%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20odd%28%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-child%28odd%29%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20first-last%28%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Afirst-child%2C%20ul%20li%3Alast-child%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20unique%28%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Aonly-child%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20not-unique%28%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anot%28%3Aonly-child%29%20%7B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20child-index%2810%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-child%281%29%20%7B%0A%20%20z-index%3A%201%3B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0Aul%20li%3Anth-child%282%29%20%7B%0A%20%20z-index%3A%202%3B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0Aul%20li%3Anth-child%283%29%20%7B%0A%20%20z-index%3A%203%3B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0Aul%20li%3Anth-child%284%29%20%7B%0A%20%20z-index%3A%204%3B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0Aul%20li%3Anth-child%285%29%20%7B%0A%20%20z-index%3A%205%3B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0Aul%20li%3Anth-child%286%29%20%7B%0A%20%20z-index%3A%206%3B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0Aul%20li%3Anth-child%287%29%20%7B%0A%20%20z-index%3A%207%3B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0Aul%20li%3Anth-child%288%29%20%7B%0A%20%20z-index%3A%208%3B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0Aul%20li%3Anth-child%289%29%20%7B%0A%20%20z-index%3A%209%3B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0Aul%20li%3Anth-child%2810%29%20%7B%0A%20%20z-index%3A%2010%3B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0A%2F*%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%20%20%20child-index%285%2C%20backward%2C%2010%29%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D*%2F%0Aul%20li%3Anth-last-child%281%29%20%7B%0A%20%20z-index%3A%209%3B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0Aul%20li%3Anth-last-child%282%29%20%7B%0A%20%20z-index%3A%208%3B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0Aul%20li%3Anth-last-child%283%29%20%7B%0A%20%20z-index%3A%207%3B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0Aul%20li%3Anth-last-child%284%29%20%7B%0A%20%20z-index%3A%206%3B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D%0A%0Aul%20li%3Anth-last-child%285%29%20%7B%0A%20%20z-index%3A%205%3B%0A%20%20background%3A%20red%3B%0A%20%20color%3A%20%23fff%3B%20%7D) IE8 is th newest one giving problems.

**Comment by benjamincharity** [comment]
Awesome. Thanks guys!
