### ISSUE TITLE
Publish to bower.io

### ISSUE THREAD

**Issue by TheJaredWilcurt** [LukyVj/family.scss#21]
It's preferable to have Sass mixins as a bower dependency so that you can include them from their bower folder, and keep the library up to date easily.

Make sure that you only have one main file in a folder called `family.scss` that others can point to and import. Having other Sass files in the same folder can cause conflicts if people are looking for stuff that has a matching name. This is why it's important to namespace your default file to `family.scss` and not something generic like `style.sass`. You can still import other sass files from subdirectories into your main file with no fear of conflicts.

Other libraries that do this:
- https://github.com/TheJaredWilcurt/scout-app#supportedbuilt-in-mixin-libraries

If you set up bower like those libraries, I'll add family.scss to Scout-App so it will come with the processor out of the box.

**Comment by Chippi** [comment]
+1

**Comment by LukyVj** [comment]
Hi, the lib will be added to bower, as they asked in #12 
I take the liberty to close this ticket to avoid the duplication.

**Comment by LukyVj** [comment]
Hey, you should now be able to `bower install family.scss` :)

**Comment by TheJaredWilcurt** [comment]
Added it to [Scout-App](https://github.com/TheJaredWilcurt/scout-app/commit/fb4ad4ebf3f8f79536a3fc86c9b3ec58d321147b). Will be in the official version when it comes out of Beta soon.
