### ISSUE TITLE
Namespace mixins

### ISSUE THREAD

**Issue by samburgers** [LukyVj/family.scss#25]
Hi, 

Really useful! Would it be a good idea to namespace each mixin, perhaps with 'fam-' or something? I know the `@include last()` mixins would at least conflict with the susy mixins. Or is there some sort of automatic way to namespace things in sass that i'm not aware of?

**Comment by LukyVj** [comment]
Hi @samburgers ! 

Thanks for opening this issue, and, by doing so, helping me with Family.scss.

I can see how and why it can be botheringto have conflicts between mixin's names when you use several Sass libraries. 
That being said, I don't think adding namespaces for Family.scss mixins would be a good idea. 

One of the main reason of the success of Family.scss, is how simple and yet semantic, the mixins names are. Adding something like `fam-` or even `f-` would make them harder to read, and to understand. 

`first()`, `last()`, `between()`, `unique()` VS `f-first()`, `f-last()`, `f-between()`, `f-unique()`. 

Honestly, I still think you made a point here, and I truly think about some improvements that I could add, to make the use of Family.scss mixins easier to deals with other libraries conflicts.

What do you think ? Maybe you already got a solution in mind ?

**Comment by l0ader3000** [comment]
Hi,

I'm having the same problem with susy and the `@include last().`

One solution would be: 
You could just provide two versions (files) of family.scss - one with, and one without the prefixes. You wouldn't bother the normal users that are not having this issue and are using the normal version without prefixes but others have a solution at hand.
Honestly: It wouldn't be that much more problematic for me to know that I have to add a prefix to my includes of family.scss - I would still use it! Also this prefix-version doesn't have to be promoted that much which would irritate users.

I really don't want to drop the use of family.scss (susy is a little bit more crucial to my workflow).

**Comment by patrickcate** [comment]
I have the same issue with the `first` and `last` mixins when used with Susy.

Having an optional namespaced version would be very helpful. The only other option I can think of is to find alternate names for those mixins which still keep their semantic meaning.

Maybe `at-first()` or `the-first()`.

**Comment by LukyVj** [comment]
Hello @samburgers, @johaWeber & @Patrickcate! 

So, due to the number of requests for this, I will add a namespaced version of Family.scss :) 
Thanks for your requests. 

I keep you updated, it should be done within the week. 

Cheers!

**Comment by patrickcate** [comment]
Any update on the namespaced version of Family.scss?

**Comment by rootical** [comment]
Hello, on this end we're interested as well in a prefixed version.
