### ISSUE TITLE
Bower dependency

### ISSUE THREAD

**Issue by mitogh** [LukyVj/family.scss#26]
Is it possible to have the library via `bower`?

Thank you. 
PS: Awesome work 👍

**Comment by LukyVj** [comment]
Hey @mitogh ! 
Thanks for the nice words. 

The lib will be added to bower, as they asked in #12 
I take the liberty to close this ticket to avoid the duplication.

**Comment by mitogh** [comment]
Great news!

Yes no problem. Thank you 🎉

**Comment by LukyVj** [comment]
Hey, you should now be able to `bower install family.scss` :)

**Comment by mitogh** [comment]
Thank you 👍

**Comment by LukyVj** [comment]
I tried to make the bower package to point the bower branch, but it seems bower only works with master. So you'll actually will bower install the whole package

**Comment by mitogh** [comment]
Thanks. 

Yes. I don't have any problem with that since most of NPM or Bower packages always comes with the whole project.

As long as we can import from `bower_componets` the `.scss` file is ok for me. 

Also I think you should create a [new release](https://github.com/LukyVj/family.scss/releases), so  we as users of this `lib` are aware of what version should we pick. 

[Here is a great text about how semantic version](http://semver.org/) works

Thank you

**Comment by LukyVj** [comment]
Wonderful, I'll read that this evening :) Thanks man!
