### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pzi** [LukyVj/family.scss#29]
Hey Lucas,

Just wondering under what kind of License Family.scss is?
The reason why I am asking this is, I was thinking of creating a Ruby gem to wrap your mixin set and open source it.

Thanks for a great resource.

Cheers
Patrik

**Comment by LukyVj** [comment]
Hey Patrik,

It's licensed under MIT at the moment, and I don't think it will change. 
You can find the License [here](https://raw.githubusercontent.com/LukyVj/family.scss/master/LICENSE)

Yey, you've got a wonderful idea!
Feel free to do so!

---

Closed by de70a99

**Comment by pzi** [comment]
Awesome, thanks @LukyVj

Will let you know when I got something presentable ;)

**Comment by LukyVj** [comment]
Sounds good!

**Comment by pzi** [comment]
Hey @LukyVj,

I finally got around to gemify family.scss and... it works™... :) 

Please have a look at [family-rails](https://github.com/pzi/family-rails) and let me know if you are happy with me publishing it to http://rubygems.org.

Cheers
Patrik
