### ISSUE TITLE
SVG icons do not render properly in FF

### ISSUE THREAD

**Issue by LukyVj** [LukyVj/family.scss#3]
In FF : 
![](http://puu.sh/p1ZUc/5899d8806c.png)
![](http://puu.sh/p1ZUl/890967aa72.png)
![](http://puu.sh/p1ZUT/d2b4c3b859.png)

VS 

Chrome / Safari
![](http://puu.sh/p1ZXO/21c30ea2e5.png)
![](http://puu.sh/p1ZXY/f13c6151e9.png)
![](http://puu.sh/p2000/1152568d5c.png)

**Comment by marcobiedermann** [comment]
It seems like `top: 60%` and `transform: translateY(-50%)` cause this strange behaviour in Firefox.

![image](https://cloud.githubusercontent.com/assets/5244986/15477431/d9dddeba-2114-11e6-81d8-b45a9cd649ff.png)

**Comment by LukyVj** [comment]
Thanks @marcobiedermann ! 
I'll take care of it now! 

You're the best!

**Comment by marcobiedermann** [comment]
@LukyVj You are very welcome. Glad to help out :)
