### ISSUE TITLE
Bower ignore

### ISSUE THREAD

**Issue by TheJaredWilcurt** [LukyVj/family.scss#30]
It looks like you're including a lot of extra stuff in the bower install that users probably won't need, you can use the `ignore` in your bower.json file to skip files from being downloaded.
- https://github.com/bower/spec/blob/master/json.md

For example, all I do is point to `bower_components/family.scss/source/src` and then I'm able to `@import family` and it will work. But I don't need any of the other files it pulled down (except maybe the bower.json itself and the readme and license if they're required by Bower).

And if you ever move the `family.scss` file to a different folder, make sure to do a major version change as some people will be pointing directly to it and that will be a breaking change for them.

**Comment by LukyVj** [comment]
Hey man, I sent you an email about that. 
I'd love to chat with you about bower. 

I would like to remove my package from the bower list to repush a clean one. But it seems you cannot remove a package from bower.. I also have several other questions. 
What would be the best way to reach you out ?

**Comment by TheJaredWilcurt** [comment]
https://gitter.im/TheJaredWilcurt

**Comment by LukyVj** [comment]
Fixed in https://github.com/LukyVj/family.scss/commit/9eb6d207ad10f4d3e7e72b3958b08e373de7eb09
