### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by KittyGiraudel** [LukyVj/family.scss#38]
You are dealing with quite complex selectors. It would be nice to see a proper test suite.

**Comment by LukyVj** [comment]
Thanks for the suggestion, Hugo.
Any suggestions about what I should use ? 
Maybe this as an entry point ? https://www.sitepoint.com/testing-sass-library/

**Comment by KittyGiraudel** [comment]
No. SassyTester is great for functions, but you want to test mixins’ output. You’ll have to roll up your own solution or use True.

**Comment by LukyVj** [comment]
https://github.com/oddbird/true

**Comment by LukyVj** [comment]
So, I checked True, it's kinda overkill for Family.scss IMO. 
I'll see if I include it on the next release or not, still not sure.
