### ISSUE TITLE
Use `last-child` in `@mixin last()` when $num = 1

### ISSUE THREAD

**Issue by narendrashetty** [LukyVj/family.scss#54]
Good job the library. It is of great use.
While going through the code I observed you didn't use pseudo `last-child` in mixin `last()`
Just like mixin `first()` we can use `last-child` when $num = 1.
Would love to know why it was avoided.

**Comment by LukyVj** [comment]
Hey @narendrashetty, thanks for opening the issue.

> :first-child is supported IE9 properly, and IE7 and IE8 sort of (see chart).
> :last-child is supported by IE9+ only.

From http://stackoverflow.com/questions/7938521/browser-support-for-css-first-child-and-last-child

But I will probably consider it for a next release.

**Comment by narendrashetty** [comment]
Thanks for your reply @LukyVj 
I would be happy to send you a PR for the same
