### ISSUE TITLE
Test using Scss Lint

### ISSUE THREAD

**Issue by marcobiedermann** [LukyVj/family.scss#69]
Hey Luke, I suggest adding a [Scss Lint](https://github.com/brigade/scss-lint) setup and automatically check it via [Travis CI](https://travis-ci.org/).

I could send you a PR later this evening, if you like to :)

**Comment by LukyVj** [comment]
Hey @marcobiedermann ! that would be rad! I have to check how to install Travis here with @Haroenv. If you suggests something, it's better :)

**Comment by Haroenv** [comment]
I'll send a PR

**Comment by LukyVj** [comment]
Thanks guys.

**Comment by marcobiedermann** [comment]
Simply add a Travis config file:

.travis.yml

```
language: ruby
rvm: 2.3.1
before_script: gem install scss_lint
script: scss-lint source/src/family.scss
```

**Comment by Haroenv** [comment]
I'd use 

``` xml
language: ruby
branches:
  only:
    - master
install:
  - bundle install
script:
  - scss-lint source/src/family.scss
```

and maybe test the middleman too
