### ISSUE TITLE
Porting this to Stylus

### ISSUE THREAD

**Issue by nusususuzu** [LukyVj/family.scss#7]
Hey, I just ported family.scss to stylus, should I send a pull requ. or open a new repo

**Comment by LukyVj** [comment]
Hey man! Thanks a lot for the support!
Create a new repo, I'll link it on the readme!

**Comment by LukyVj** [comment]
Just give me the link here once you're done with it :)

**Comment by nusususuzu** [comment]
thank you :) here you are 👍 
https://github.com/nusususuzu/family.styl

**Comment by LukyVj** [comment]
Fixed in 7190ff30562b375ea5aa1e38482d29d31a97196d
