### ISSUE TITLE
Fix modal about on mobile

### ISSUE THREAD

**Issue by LukyVj** [LukyVj/family.scss#75]

**Comment by pzi** [comment]
Based on this screenshot from "iPhone6" (devtools):
![image](https://user-images.githubusercontent.com/2037851/27118377-97fc204a-510d-11e7-935a-142eb6b8da3a.png)

- fix `width` of modal
- fix buttons at the bottom of modal
- allow modal content to be scrolled?
- disable scrolling on `body`
- maybe reduce `font-size` a bit?
- fwiw, could use http://www.humaan.com/modaal/
