### ISSUE TITLE
About the main file

### ISSUE THREAD

**Issue by x09326** [LukyVj/family.scss#79]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).

Could you tell me which files should be added?
Thanks for your help!
https://github.com/cdnjs/cdnjs/issues/8550

**Comment by LukyVj** [comment]
Hey, thanks for participating :) 
Here is the file. 

[`https://github.com/LukyVj/family.scss/blob/master/source/src/_family.scss`](https://github.com/LukyVj/family.scss/blob/master/source/src/_family.scss]
