### ISSUE TITLE
Mixin "first" does not accept a content block.

### ISSUE THREAD

**Issue by 1stevengrant** [LukyVj/family.scss#80]
Trying to do something simple as 

```
@include first(1) {
    background: blue;
  }
```

and it won't compile.

**Comment by LukyVj** [comment]
Hey, thanks for this. 
I'm gonna check.

You confirm me that you included the mixin in a parent selecor, right ? 

```
li {
 @include first(5) { css } 
}
```

?

**Comment by 1stevengrant** [comment]
Doh! What I want here is actually `nth-of-type`

**Comment by LukyVj** [comment]
Ok, because what you asked works :) 

http://codepen.io/LukyVj/pen/534f3cbae884e71fcb7aee3403467ce3

**Comment by 1stevengrant** [comment]
Strange - even using your example here I get the same error in my compile...

**Comment by LukyVj** [comment]
What is the error message ?
