### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by x09326** [LukyVj/family.scss#82]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).

But I found that your license in `package.json` is different from the `LICENCE`.
Could you tell me which is able to use?
Thanks.
https://github.com/cdnjs/cdnjs/pull/8652#event-796886258

**Comment by pzi** [comment]
@x09326 I am curious to know how that is going to work – hosting it on cdnjs – given _family.scss_ has no actual output after the **preprocessor** is done with it? It's a mixin library that is meant to be consumed by another Sass file by a preprocessor.

**Comment by x09326** [comment]
@PeterDaveHello
Is cdnjs okay for that?

**Comment by PeterDaveHello** [comment]
@x09326 please point out the part you said "different" so that we can easily discuss here.

**Comment by x09326** [comment]
Because the `LICENCE` said that the license is **MIT**.
But the license in `package.json` is **ISC**.

**Comment by PeterDaveHello** [comment]
Okay so we better figure the right license here.

**Comment by LukyVj** [comment]
Hi, my bad. The right license is MIT.

**Comment by LukyVj** [comment]
Ill fix that today.

**Comment by PeterDaveHello** [comment]
Thanks @LukyVj !

**Comment by LukyVj** [comment]
Done :)  https://github.com/LukyVj/family.scss

**Comment by x09326** [comment]
@LukyVj 
Thank you!

**Comment by PeterDaveHello** [comment]
@x09326 don't you close this issue?
